wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.15
    start_time: 1666774144.307851
    t:
      1:
      - 2
      - 3
      - 12
      - 45
      - 55
      2:
      - 2
      - 3
      - 12
      - 45
      - 55
      3:
      - 16
      - 23
      4: 3.9.15
      5: 0.13.4
      8:
      - 5
batch_size:
  desc: null
  value: 1
clip_parameter:
  desc: null
  value: 1.0
learning_rate:
  desc: null
  value: 1.0e-05
model_config:
  desc: null
  value:
    block_config:
      dropout_rate_att: 0.5
      dropout_rate_ffd: 0.1
      latent_dim: 512
      latent_ffd_dim: 1203
      n_heads: 8
      training: true
    dropout_embedding: 0.5
    img_params:
    - 224
    - 16
    n_blocks: 3
    output_dim: 102
num_epochs:
  desc: null
  value: 3
warmup_epochs:
  desc: null
  value: 1
weight_decay:
  desc: null
  value: 0.001
