seed: 42
config:
  model_config: 
    n_blocks: 10
    block_config:
      latent_dim: 1024
      latent_ffd_dim: 1024
      n_heads: 8
      dropout_rate_ffd: .1
      dropout_rate_att: .1
    dropout_embedding: .1
    img_params: [224, 32] # (image_size, patch_size)

  weight_decay: 0.00001
  learning_rate: 0.001
  warmup_epochs: 10
  num_epochs: 40
  clip_parameter: 2.
  batch_size: 40

logger_kwargs:
  project_name: training-ViT-with-flax
  wandb_config: 
    job_type: train_and_eval
    name: run

dataset_kwargs: 
  dataset_name: caltech101
  validation_split: 0.5
  force_download: true
